name: Build ColorPicker Demo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant Permission
        run: chmod +x gradlew

      - name: Build Sample App
        # 关键修改：直接运行 app 模块的编译命令
        run: ./gradlew :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ColorPicker-Sample-App
          # 明确指向演示 App 的生成路径
          path: app/build/outputs/apk/debug/*.apk
